### PR TITLE
Use an exception with no stack as flow control for getDefaultValue

### PR DESCRIPTION
**Pull request by jhspaybar**

### CODE REVIEW

**Comment by jhspaybar** [comment]
This should address https://github.com/Netflix/archaius/issues/486 .  We still use exceptions for flow control, but just don't make the stack which is the expensive part.

**Comment by elandau** [comment]
How about we just deprecate all the methods where a default value is not provided.  That path does not throw an exception if the key is not found.

**Comment by jhspaybar** [comment]
@elandau the issue is this block ```protected <T> T getValueWithDefault(Class<T> type, String key, T defaultValue) {
        try {
            return getValue(type, key);
        } catch (NoSuchElementException e) {
            return defaultValue;
        }
    }```
it doesn't bubble an exception outside of archaius, but the throw/catch here to use the default value is actually what causes the excess CPU usage.

**Comment by elandau** [comment]
Ah, I was just looking at the getString() case.  In that case let's flip the implementation between getValue and getValueWithDefault so that getValue() throws an exception if the value is null.

**Pull request closed without merging**
